<?php
$fields = array("Mechanical Power Engineering",
"Computer Engineering",
"Electrical Power Engineering",
"Communication Systems Engineering",
"Civil Engineering",
"Architectural Engineering",
"Marketing",
"Sales",
"Accounting",
"Advertisement",
"Pharmaceutical",
"Cardiology",
"Dermatology",
"Immunology",
"Neurology",
"Sports",
"Miscellaneous");
$cities = array("Cairo",
"Alexandria",
"Gizeh",
"Shubra El-Kheima",
"Port Said",
"Suez",
"Luxor",
"al-Mansura",
"El-Mahalla El-Kubra",
"Tanta",
"Asyut",
"Ismailia",
"Fayyum",
"Zagazig",
"Aswan",
"Damietta",
"Damanhur",
"al-Minya",
"Beni Suef",
"Qena",
"Sohag",
"Hurghada",
"th of October City",
"Shibin El Kom",
"Banha",
"Kafr el-Sheikh",
"Arish",
"Mallawi",
"th of Ramadan City",
"Bilbais",
"Marsa Matruh",
"Idfu",
"Mit Ghamr",
"Al-Hamidiyya",
"Desouk",
"Qalyub",
"Abu Kabir",
"Kafr el-Dawwar",
"Girga",
"Akhmim",
"Matareya");
$periods = array("Not Specified", "Summer Internship", "Winter Internship");
$types = array("Full-time", "Part-time");
?>